In [2]:
#      NUMPY FULL COURSE
# DIMENSION IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8])
print(a.ndim)

b=np.array([[2,4,6,8],[10,12,14,16]])
print(b.ndim)

c=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(c.ndim)

1
2
3


In [5]:
# CREATING SPECIAL TYPE OF ARRAY IN NUMPY
import numpy as np
a=np.zeros(4)
b=np.zeros([4,2])
print(a)
print(b)

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
import numpy as np
a=np.ones(4)
b=np.ones([2,2])
print(a)
print(b)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [10]:
import numpy as np
a=np.empty(6)
print(a)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.06811083e-306
 1.89146896e-307 7.56571288e-307]


In [16]:
import numpy as np
a=np.arange(9)
b=np.arange(4,9)
c=np.arange(1,9,(2))
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8]
[4 5 6 7 8]
[1 3 5 7]


In [17]:
import numpy as np
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
# DATA TYPES IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8],dtype=np.float64)
b=np.float32(a)
print(a.dtype)
print(b.dtype)

float64
float32


In [24]:
# CREATING RANDOM VALUES IN NUMPY ARRAY.
import numpy as np
import random
a=np.random.rand(4)
print(a)

[0.21781676 0.07974622 0.16814249 0.02822873]


In [25]:
import numpy as np
import random
a=np.random.randn(4)
print(a)

[-0.55001312  0.55722332 -0.94741484  0.63168069]


In [27]:
import numpy as np
import random
a=np.random.ranf(4)
print(a)

[0.88457247 0.02752122 0.65368107 0.06925105]


In [28]:
import numpy as np
import random
a=np.random.randint(10,40,(12))
print(a)

[25 15 14 15 27 23 24 26 26 25 12 20]


In [29]:
# SHAPE FUNCTION IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8])
print(a.shape)

(4,)


In [30]:
import numpy as np
a=np.array([[2,4,6,8],[10,12,14,16]])
print(a.shape)

(2, 4)


In [31]:
import numpy as np
a=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(a.shape)

(2, 2, 4)


In [33]:
# RESHAPE FUNCTION IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8,10,12,14,16])
print(a)
print(a.shape)
# RESAHPE 1D ARRAY INTO 2D ARRAY
b=a.reshape(4,2)
print(b)
print(b.shape)

[ 2  4  6  8 10 12 14 16]
(8,)
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
(4, 2)


In [34]:
import numpy as np
a=np.array([2,4,6,8,10,12,14,16])
print(a)
print(a.shape)
# RESAHPE 1D ARRAY INTO 3D ARRAY
b=a.reshape(1,4,2)
print(b)
print(b.shape)

[ 2  4  6  8 10 12 14 16]
(8,)
[[[ 2  4]
  [ 6  8]
  [10 12]
  [14 16]]]
(1, 4, 2)


In [36]:
import numpy as np
a=np.array([[2,4,6,8],[10,12,14,16]])
print(a)
print(a.shape)

# RESHAPE 2D ARRAY INTO 3D ARRAY
b=a.reshape(1,4,2)
print(b)
print(b.shape)

[[ 2  4  6  8]
 [10 12 14 16]]
(2, 4)
[[[ 2  4]
  [ 6  8]
  [10 12]
  [14 16]]]
(1, 4, 2)


In [37]:
import numpy as np
a=np.array([[2,4,6,8],[10,12,14,16]])
print(a)
print(a.shape)

# RESHAPE 2D ARRAY INTO 1D ARRAY
b=a.reshape(-1)
print(b)
print(b.shape)

[[ 2  4  6  8]
 [10 12 14 16]]
(2, 4)
[ 2  4  6  8 10 12 14 16]
(8,)


In [38]:
import numpy as np
a=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(a)
print(a.shape)

# RESHAPE 3D ARRAY INTO 1D ARRAY
b=a.reshape(-1)
print(b)
print(b.shape)

[[[ 2  4  6  8]
  [10 12 14 16]]

 [[18 20 22 24]
  [26 28 30 32]]]
(2, 2, 4)
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]
(16,)


In [39]:
import numpy as np
a=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(a)
print(a.shape)

# RESHAPE 3D ARRAY INTO 2D ARRAY
b=a.reshape(4,4)
print(b)
print(b.shape)

[[[ 2  4  6  8]
  [10 12 14 16]]

 [[18 20 22 24]
  [26 28 30 32]]]
(2, 2, 4)
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
(4, 4)


In [40]:
# INDEXING IN NUMPY ARRAY

import numpy as np
a=np.array([2,4,6,8])
print(a[0])
print(a[3])

2
8


In [44]:
import numpy as np
a=np.array([[2,4,6,8],[10,12,14,16]])
print(a[0,1])
print(a[1,2])

4
14


In [46]:
import numpy as np
a=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(a[0,1,1])
print(a[1,0,0])

12
18


In [47]:
# SLICING IN NUMPY ARRAY

import numpy as np
a=np.array([2,4,6,8])
print(a[0:3])

[2 4 6]


In [51]:
import numpy as np
a=np.array([[2,4,6,8],[10,12,14,16]])
print(a[0,0:3])
print(a[0:2,1])
print(a[0:2,0:3])

[2 4 6]
[ 4 12]
[[ 2  4  6]
 [10 12 14]]


In [53]:
import numpy as np
a=np.array([[[2,4,6,8],[10,12,14,16]],[[18,20,22,24],[26,28,30,32]]])
print(a[0,0,0:2])
print(a[1,1,0:4])

[2 4]
[26 28 30 32]


In [59]:
# COPY IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8])
b=a.copy()
a[0]=20
print(a)
print(b)

[20  4  6  8]
[2 4 6 8]


In [60]:
# VIEW IN NUMPY ARRAY
import numpy as np
a=np.array([2,4,6,8])
b=a.view()
a[0]=20
print(a)
print(b)

[20  4  6  8]
[20  4  6  8]


In [61]:
# SEARCH FUNCTION
a=np.array([2,4,6,8,8,2,4,7,5,8,2,17,52,9,5,8,8])
b=np.where(a==8)
print(b)

(array([ 3,  4,  9, 15, 16], dtype=int64),)


In [62]:
# SEARCH SORTED
import numpy as np
a=np.array([2,4,6,8])
b=np.searchsorted(a,5)
print(b)

2


In [68]:
# SORT
a=np.array([2,4,6,8,8,2,4,7,5,8,2,18,52,9,5,8,8])
print(np.sort(a))

[ 2  2  2  4  4  5  5  6  7  8  8  8  8  8  9 18 52]


In [65]:
# SHUFFLE FUNCTION
import numpy as np
import random
a=np.array([2,4,6,8])
np.random.shuffle(a)
print(a)

[8 2 4 6]


In [67]:
# UNIQUE FUNCTION
import numpy as np
a=np.array([2,4,6,8,8,2,4,7,5,8,2,18,52,9,5,8,8])
b=np.unique(a)
print(b)

[ 2  4  5  6  7  8  9 18 52]
