# NUMPY TRICKS

# np.expand_dims() :- with the help of this function we can change the dimension of an array.

In [3]:
import numpy as np
a=np.array([2,4,6,8])
np.expand_dims(a,axis=0)

array([[2, 4, 6, 8]])

In [2]:
np.expand_dims(a,axis=1)

array([[2],
       [4],
       [6],
       [8]])

# WHERE :-
# whatever the condition written inside the where block is true then it will return the index of an element.

In [6]:
import numpy as np
a=np.arange(4,20)
np.where(a>8)


(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=int64),)

In [7]:
np.where(a>=8,28,a)

array([ 4,  5,  6,  7, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28])

# argmax and argmin :- return the index of maximum and minimum elements row wise or column wise

In [13]:
import numpy as np
a=np.arange(24,48).reshape(4,6)
a
np.argmax(a,axis=0)
np.argmax(a,axis=1)

array([5, 5, 5, 5], dtype=int64)

In [14]:
a

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [16]:
np.argmin(a,axis=0)
np.argmin(a,axis=1)

array([0, 0, 0, 0], dtype=int64)

# cumsum

In [19]:
import numpy as np
a=np.array([2,4,6,8])
np.cumsum(a)

array([ 2,  6, 12, 20])

# cumprod

In [20]:
import numpy as np
a=np.array([2,4,6,8])
np.cumprod(a)

array([  2,   8,  48, 384])

# PERCENTILE

In [22]:
a=np.array([418,458])
np.percentile(a,50)

438.0

# isin:- jb ek sath multiple values ko serach krna hai then we used it

In [24]:
import numpy as np
a=np.array([2,4,6,8])
a[np.isin(a,[4,6,2,18])]

array([2, 4, 6])